In [1]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
print (a)

[1 2 3 4 5]


In [4]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
d=np.ones((3,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
print(c)

[[ 6  8]
 [10 12]]


In [11]:
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
f=a*b
print(f)

[[ 5 12]
 [21 32]]


In [12]:
g=np.array([[1,2],[3,4]])
h=np.array([[5,6],[7,8]])
i=np.dot(g,h)
print(i)

[[19 22]
 [43 50]]
